release:
  prerelease: auto
  draft: false

builds:
  - id: linux-build
    dir: ./cmd/xeol
    binary: xeol
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x
    # set the modified timestamp on the output binary to the git timestamp to ensure a reproducible build
    mod_timestamp: &build-timestamp '{{ .CommitTimestamp }}'
    env: &build-env
      - CGO_ENABLED=0
    ldflags: &build-ldflags |
      -w
      -s
      -extldflags '-static'
      -X github.com/xeol-io/xeol/internal/version.version={{.Version}}
      -X github.com/xeol-io/xeol/internal/version.syftVersion={{.Env.SYFT_VERSION}}
      -X github.com/xeol-io/xeol/internal/version.gitCommit={{.Commit}}
      -X github.com/xeol-io/xeol/internal/version.buildDate={{.Date}}
      -X github.com/xeol-io/xeol/internal/version.gitDescription={{.Summary}}

  - id: darwin-build
    dir: ./cmd/xeol
    binary: xeol
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: *build-timestamp
    env: *build-env
    ldflags: *build-ldflags

  - id: windows-build
    binary: xeol
    goos:
      - windows
    goarch:
      - amd64
    mod_timestamp: *build-timestamp
    env: *build-env
    ldflags: *build-ldflags

archives:
  - id: linux-archives
    builds:
      - linux-build

  - id: darwin-archives
    builds:
      - darwin-build

  - id: windows-archives
    format: zip
    builds:
      - windows-build

nfpms:
  - license: "Apache 2.0"
    maintainer: "noqcks"
    homepage: &website "https://github.com/xeol-io/xeol"
    description: &description "A scanner for end-of-life (EOL) software in container images, filesystems, and SBOMs"
    formats:
      - rpm
      - deb

brews:
  - tap:
      owner: xeol-io
      name: homebrew-xeol
    ids:
      - darwin-archives
      - linux-archives
    homepage: *website
    description: *description
    license: "Apache License 2.0"
