FROM docker@sha256:9e6dbb25d3c0e1e2d222c8a3f074cb8240d1a716d0c6868f76eb3d5a4dfb174c

ENV GO_VERSION=1.20.7
ENV PATH=$PATH:/usr/local/go/bin:/usr/bin/env:/root/go/bin

WORKDIR /xeol

COPY go.mod go.sum Makefile /xeol/
COPY .github .github

RUN docker-entrypoint.sh sh && \
    apk update && \
    apk add make curl build-base bash ncurses openssl && \
    curl -OL https://golang.org/dl/go${GO_VERSION}.linux-amd64.tar.gz && \
    tar -C /usr/local -xf go${GO_VERSION}.linux-amd64.tar.gz && \
    go install github.com/go-delve/delve/cmd/dlv@d9d8f4ad8c9b0c9cc74b100fb1afb109f89dd493 && \
    # fix all line terminations in .sh scripts for windows
    find . -name "*.sh" -exec sed -i -e 's/\r$//' {} + && \
    make bootstrap
