FROM gcr.io/distroless/static-debian11:debug@sha256:af644bb6810b7118be6c378c909307c6a9e2a9813d792b541c3562e1a2b062b3


# create the /tmp dir, which is needed for image content cache
WORKDIR /tmp

COPY xeol /

ARG BUILD_DATE
ARG BUILD_VERSION
ARG VCS_REF
ARG VCS_URL

LABEL org.opencontainers.image.created=$BUILD_DATE
LABEL org.opencontainers.image.title="xeol"
LABEL org.opencontainers.image.description="A scanner for end-of-life (EOL) software in container images, filesystems, and SBOMs"
LABEL org.opencontainers.image.source=$VCS_URL
LABEL org.opencontainers.image.revision=$VCS_REF
LABEL org.opencontainers.image.vendor="Xeol"
LABEL org.opencontainers.image.version=$BUILD_VERSION
LABEL org.opencontainers.image.licenses="Apache-2.0"
LABEL io.artifacthub.package.readme-url="https://raw.githubusercontent.com/xeol-io/xeol/main/README.md"
LABEL io.artifacthub.package.license="Apache-2.0"

ENTRYPOINT ["/xeol"]
