FROM docker@sha256:d33ffba5909705d375ef1a99bb69fe6e21d80482134283226b119acf18bb08b4

ENV GO_VERSION=1.23.2
ENV PATH=$PATH:/usr/local/go/bin:/usr/bin/env:/root/go/bin

WORKDIR /xeol

COPY go.mod go.sum Makefile /xeol/
COPY .github .github

RUN docker-entrypoint.sh sh && \
    apk add --no-cache make curl build-base bash ncurses openssl && \
    curl -OL https://golang.org/dl/go${GO_VERSION}.linux-amd64.tar.gz && \
    tar -C /usr/local -xf go${GO_VERSION}.linux-amd64.tar.gz && \
    go install github.com/go-delve/delve/cmd/dlv@d9d8f4ad8c9b0c9cc74b100fb1afb109f89dd493 && \
    # fix all line terminations in .sh scripts for windows
    find . -name "*.sh" -exec sed -i -e 's/\r$//' {} + && \
    make bootstrap
